"""Original modular Scorpion asset. Run with Blender 5.2 --background --python.

All authored coordinates are Godot metres (X right, Y up, -Z forward).
The glTF exporter converts the Blender scene back to that convention.
Portable bitmap PBR maps are generated here; no procedural shader is required
by the game. The resulting meshes are joined by mechanical moving part.
"""
import bpy, bmesh, math, json, random, sys, struct, importlib
sys.dont_write_bytecode = True
from pathlib import Path
from mathutils import Vector, Matrix
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'battlebots/assets/models/scorpion_source'
RUNTIME = ROOT / 'battlebots/assets/models/scorpion_runtime'
SOURCE.mkdir(parents=True, exist_ok=True)
RUNTIME.mkdir(parents=True, exist_ok=True)
(SOURCE / '.gdignore').write_text('')
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
random.seed(3187)

def gv(p): return Vector((p[0], -p[2], p[1]))
def godot(p): return [round(p.x, 6), round(p.z, 6), round(-p.y, 6)]
def linear(c): return c / 12.92 if c <= .04045 else ((c + .055) / 1.055) ** 2.4
def srgb(rgb): return tuple(linear(v) for v in rgb)

N = 1024
Y, X = np.mgrid[0:N, 0:N].astype(np.float32)
u, v = X / (N-1), Y / (N-1)
rng = np.random.default_rng(571)
grain = rng.random((N,N), dtype=np.float32)
noise = grain.copy()
for scale in (2, 4, 9, 19):
    noise += (np.sin(u * scale * 7 + .7) * np.cos(v * scale * 8 + .23) + 1) * .12
edge = np.minimum.reduce([u, v, 1-u, 1-v])
wear_noise=(np.sin(u*87+np.sin(v*47))*np.cos(v*61+np.cos(u*39))+1)*.5
chip = (edge < (.0015 + wear_noise*.007)) & (wear_noise>.60)
# Nonuniform islands of exposed substrate and directional abrasion.
for _ in range(74):
    cx, cy = rng.uniform(0,1,2)
    rx, ry = rng.uniform(.003,.026), rng.uniform(.002,.020)
    blot = ((u-cx)/rx)**2 + ((v-cy)/ry)**2
    angle=np.arctan2((v-cy)/ry,(u-cx)/rx)
    broken_edge=.57+.19*np.sin(angle*7+cx*19)+.12*np.cos(angle*13+cy*27)
    chip |= (blot < broken_edge*(.67+wear_noise*.43))
scratches = np.zeros((N,N), dtype=bool)
for _ in range(20):
    cx,cy=rng.uniform(.02,.98,2)
    length=rng.uniform(.005,.052)
    scratches |= (abs((v-cy) - (u-cx)*.32)<rng.uniform(.0003,.0012)) & (abs(u-cx)<length)
chip |= scratches

def save_image(name, data, noncolor=False):
    image=bpy.data.images.new(name,width=N,height=N,alpha=True)
    image.colorspace_settings.name='Non-Color' if noncolor else 'sRGB'
    rgba=np.ones((N,N,4),dtype=np.float32)
    rgba[:,:,:3]=np.clip(data,0,1)
    image.pixels.foreach_set(rgba.reshape(-1))
    image.filepath_raw=str(RUNTIME/(name+'.png'))
    image.file_format='PNG'
    image.save()
    # Generated byte buffers and file textures can be sampled differently.
    # Reload the saved 8-bit sRGB/Non-Color PNG so Blender and Godot see exactly
    # the same portable texture bytes. Artist colors are encoded sRGB inputs.
    image.source='FILE'
    image.reload()
    image.colorspace_settings.name='Non-Color' if noncolor else 'sRGB'
    return image

def make_maps(name, base, metal, rough, painted=True, stripe=False):
    color=np.ones((N,N,3),dtype=np.float32)*np.array(base,dtype=np.float32)
    color *= (.965 + grain[:,:,None]*.045 + (noise[:,:,None]-.8)*.025)
    if stripe:
        # Correct aspect for the hammer's narrow, tall insert: broad 45 degree
        # bands in world space instead of stretched pinstripes.
        bands=((u*.60+v*2.20)%1)<.44
        color[bands]*=.105
    marks=chip if painted else (scratches & (grain>.35))
    color[marks]=np.array((.25,.245,.225))*(.8+grain[marks,None]*.45)
    # Rust catches only deep paint chips; exposed edges stay bright steel.
    rust=marks & (grain<.07) & (edge>.023)
    color[rust]=(.19,.083,.027)
    mr=np.ones((N,N,3),dtype=np.float32)
    mr[:,:,1]=rough+(grain-.5)*.07
    mr[:,:,2]=metal
    mr[marks,1]=.32+(grain[marks]-.5)*.1
    mr[marks,2]=.96
    height=(grain-.5)*.035
    height[marks]-=.1
    dx=(np.roll(height,1,1)-np.roll(height,-1,1))*.25
    dy=(np.roll(height,1,0)-np.roll(height,-1,0))*.25
    normal=np.stack([.5+dx,.5+dy,np.ones_like(grain)],2)
    return save_image(name+'_base',color),save_image(name+'_orm',mr,True),save_image(name+'_normal',normal,True)

def textured(name, color, metal, rough, painted=True, stripe=False):
    a,m,n=make_maps(name,color,metal,rough,painted,stripe)
    mat=bpy.data.materials.new(name)
    mat.use_nodes=True
    nodes=mat.node_tree.nodes; links=mat.node_tree.links
    bs=nodes.get('Principled BSDF')
    bs.inputs['Metallic'].default_value=metal
    bs.inputs['Roughness'].default_value=rough
    for image,kind in [(a,'albedo'),(m,'orm'),(n,'normal')]:
        node=nodes.new('ShaderNodeTexImage'); node.image=image
        if kind=='albedo': links.new(node.outputs['Color'],bs.inputs['Base Color'])
        if kind=='orm':
            split=nodes.new('ShaderNodeSeparateColor')
            links.new(node.outputs['Color'],split.inputs['Color'])
            links.new(split.outputs['Green'],bs.inputs['Roughness'])
            links.new(split.outputs['Blue'],bs.inputs['Metallic'])
        if kind=='normal':
            nm=nodes.new('ShaderNodeNormalMap'); nm.inputs['Strength'].default_value=.3
            links.new(node.outputs['Color'],nm.inputs['Color'])
            links.new(nm.outputs['Normal'],bs.inputs['Normal'])
    mat.diffuse_color=(*srgb(color),1)
    return mat

def simple(name,color,metal,rough,emission=0):
    mat=bpy.data.materials.new(name);mat.use_nodes=True
    bs=mat.node_tree.nodes.get('Principled BSDF')
    bs.inputs['Base Color'].default_value=(*srgb(color),1)
    bs.inputs['Metallic'].default_value=metal
    bs.inputs['Roughness'].default_value=rough
    if emission:
        bs.inputs['Emission Color'].default_value=(*srgb(color),1)
        bs.inputs['Emission Strength'].default_value=emission
    mat.diffuse_color=(*srgb(color),1)
    return mat

orange=textured('Scorpion_OrangeCeramic',(.86,.40,.060),.48,.40)
hazard=textured('Scorpion_Hazard',(.87,.60,.063),.48,.46,stripe=True)
dark=textured('Scorpion_BlackenedSteel',(.13,.14,.145),.82,.41,False)
steel=simple('Scorpion_ExposedTitanium',(.43,.445,.44),.91,.34)
chrome=simple('Scorpion_HydraulicChrome',(.65,.68,.69),1,.24)
rubber=simple('Scorpion_Rubber',(.035,.045,.055),.12,.72)
brass=simple('Scorpion_Brass',(.52,.34,.15),.86,.3)
white=simple('Scorpion_IvoryStencil',(.79,.82,.75),.3,.49)
amber=simple('Scorpion_AmberOptics',(1,.39,.035),.3,.23,2.5)
red=simple('Scorpion_RedOptics',(.88,.018,.005),.15,.2,2)

groups={}
def part(name,at=(0,0,0),parent=None):
    obj=bpy.data.objects.new(name,None)
    bpy.context.collection.objects.link(obj)
    obj.empty_display_type='ARROWS';obj.empty_display_size=.12
    obj.location=gv(at)
    if parent:
        obj.parent=parent
        obj.location=gv(at)-parent.matrix_world.translation
    bpy.context.view_layer.update()
    groups[obj]=[]
    return obj

root=part('Scorpion')
body=part('Body',parent=root)
tail0=part('TailBase',(0,.22,.68),root)
tail1=part('TailUpper',(0,.98,.95),tail0)
tail2=part('TailFore',(0,1.73,.28),tail1)
hammer=part('HammerHead',(0,1.51,-.88),tail2)
gun=part('GunMount',(.66,.22,-.42),root)
rotor=part('GunRotor',(.66,.27,-.95),gun)
upper=part('LegUpper');lower=part('LegLower');foot=part('LegFoot')

def mesh(name,verts,faces,mat,group,bevel=0):
    data=bpy.data.meshes.new(name)
    data.from_pydata([gv(p) for p in verts],[],faces);data.update()
    bm=bmesh.new();bm.from_mesh(data);bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces));bm.to_mesh(data);bm.free();data.update()
    obj=bpy.data.objects.new(name,data);bpy.context.collection.objects.link(obj)
    data.materials.append(mat)
    uv=data.uv_layers.new(name='UVMap')
    for poly in data.polygons:
        # Planar face UVs with a small deterministic per-face offset/rotation.
        coords=[data.vertices[i].co for i in poly.vertices]
        normal=poly.normal
        axis=max(range(3),key=lambda i:abs(normal[i]))
        axes=[i for i in range(3) if i!=axis]
        vals=[[p[a] for p in coords] for a in axes]
        mins=[min(a) for a in vals]; spans=[max(a)-min(a) for a in vals]
        for j,loop in enumerate(poly.loop_indices):
            uv.data[loop].uv=tuple(.015+.97*(vals[i][j]-mins[i])/max(spans[i],.001) for i in range(2))
    if bevel:
        mod=obj.modifiers.new('Machined edge radii','BEVEL')
        mod.width=bevel;mod.segments=3;mod.affect='EDGES';mod.material=0
        mod.limit_method='ANGLE';mod.angle_limit=.60
        mod=obj.modifiers.new('Weighted corner normals','WEIGHTED_NORMAL');mod.keep_sharp=True;mod.weight=40
    groups[group].append(obj)
    return obj

def box(name,at,size,mat,group,bevel=.009):
    a=Vector(at);s=Vector(size)*.5
    verts=[tuple(a+Vector((x*s.x,y*s.y,z*s.z))) for x,y,z in [(-1,-1,-1),(1,-1,-1),(1,1,-1),(-1,1,-1),(-1,-1,1),(1,-1,1),(1,1,1),(-1,1,1)]]
    faces=[(0,3,2,1),(4,5,6,7),(0,1,5,4),(3,7,6,2),(1,2,6,5),(0,4,7,3)]
    return mesh(name,verts,faces,mat,group,bevel)

def cylinder(name,a,b,r,mat,group,n=24,r2=None,bevel=.003):
    n=min(n,12 if r<.07 else 32)
    if r<.07:bevel=0
    a=Vector(a);b=Vector(b);axis=(b-a).normalized()
    tangent=axis.cross(Vector((0,1,0)))
    if tangent.length<.1:tangent=axis.cross(Vector((1,0,0)))
    tangent.normalize();bit=axis.cross(tangent)
    r2=r if r2 is None else r2
    verts=[]
    for p,rad in [(a,r),(b,r2)]:
        for i in range(n): verts.append(tuple(p+(tangent*math.cos(i*math.tau/n)+bit*math.sin(i*math.tau/n))*rad))
    faces=[tuple(reversed(range(n))),tuple(range(n,n*2))]+[(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)]
    obj=mesh(name,verts,faces,mat,group,bevel)
    for poly in obj.data.polygons:poly.use_smooth=len(poly.vertices)==4
    return obj

def ring(name,at,axis,outer,inner,width,mat,group,n=32):
    n=min(n,12 if outer<.08 else 24)
    a=Vector(at);d=Vector(axis).normalized()
    t=d.cross(Vector((0,1,0)))
    if t.length<.1:t=d.cross(Vector((1,0,0)))
    t.normalize();b=d.cross(t)
    verts=[]
    for dep,rad in [(-width/2,outer),(width/2,outer),(-width/2,inner),(width/2,inner)]:
        for i in range(n):verts.append(tuple(a+d*dep+(t*math.cos(i*math.tau/n)+b*math.sin(i*math.tau/n))*rad))
    faces=[]
    for i in range(n):
        j=(i+1)%n
        faces.extend([(i,j,j+n,i+n),(2*n+i,3*n+i,3*n+j,2*n+j),(i,2*n+i,2*n+j,j),(i+n,j+n,3*n+j,3*n+i)])
    obj=mesh(name,verts,faces,mat,group,0)
    for p in obj.data.polygons:p.use_smooth=True
    return obj

def bolt(at,axis,group,r=.019):
    p=Vector(at);d=Vector(axis)
    cylinder('Recess washer',p-d*.006,p+d*.005,r*1.47,dark,group,8,bevel=0)
    cylinder('Hex fastener',p+d*.004,p+d*.017,r,steel,group,6,bevel=0)
    cylinder('Bolt socket',p+d*.0171,p+d*.018,r*.4,rubber,group,6,bevel=0)

def beam(name,a,b,width,depth,mat,group):
    a,b=Vector(a),Vector(b);d=(b-a).normalized()
    right=Vector((1,0,0));front=d.cross(right).normalized()
    verts=[]
    for center in [a,b]:
        for x,z in [(-1,-1),(1,-1),(1,1),(-1,1)]:verts.append(tuple(center+right*width*x/2+front*depth*z/2))
    return mesh(name,verts,[(0,3,2,1),(4,5,6,7),(0,1,5,4),(3,7,6,2),(1,2,6,5),(0,4,7,3)],mat,group,.014)

def tube(name,points,r,mat,group):
    pts=[Vector(p) for p in points]
    for a,b in zip(pts,pts[1:]):cylinder(name,a,b,r,mat,group,10,bevel=0)

def textmesh(text,at,size,group,front=False):
    curve=bpy.data.curves.new('Engraving','FONT');curve.body=text;curve.size=size;curve.extrude=.0003
    curve.resolution_u=2
    curve.align_x='CENTER';curve.space_character=1.08
    obj=bpy.data.objects.new('Stencil '+text,curve);bpy.context.collection.objects.link(obj)
    obj.location=gv(at)
    # Blender text XY faces +Z = Godot up. For front face normal -Z rotate 90 X.
    if front:
        obj.rotation_euler.x=math.pi/2
        obj.rotation_euler.z=math.pi
    else:obj.rotation_euler.z=math.pi
    curve.materials.append(white)
    bpy.context.view_layer.objects.active=obj;obj.select_set(True)
    bpy.ops.object.convert(target='MESH');obj.select_set(False)
    groups[group].append(obj)

def joint(at,group,r=.14,width=.43):
    p=Vector(at)
    cylinder('Sealed joint housing',p-Vector((width/2,0,0)),p+Vector((width/2,0,0)),r,dark,group,32,bevel=.005)
    for s in [-1,1]:
        q=p+Vector((s*(width/2+.009),0,0))
        ring('Machined race',q,(1,0,0),r*.91,r*.73,.023,steel,group)
        cylinder('Hub cover',q-Vector((.008,0,0)),q+Vector((.008,0,0)),r*.70,orange,group,24,bevel=.003)
        bolt(q+Vector((s*.013,0,0)),(s,0,0),group,r*.19)
        bolt_count=4 if group in (upper,lower) else 6
        for i in range(bolt_count):
            t=i*math.tau/bolt_count
            bolt(q+Vector((s*.014,math.sin(t)*r*.78,math.cos(t)*r*.78)),(s,0,0),group,.009)

# Chassis silhouette: three six-sided rings, strongly narrowing toward the roof.
profile=[(-.40,-.82),(.40,-.82),(.80,0),(.40,.82),(-.40,.82),(-.80,0)]

def ring_shell(name,rings,mat,group,bevel=.018):
    verts=[(x*scale,y,z*scale) for y,scale in rings for x,z in profile]
    n=len(profile);faces=[tuple(reversed(range(n))),tuple(range((len(rings)-1)*n,len(rings)*n))]
    for row in range(len(rings)-1):
        for i in range(n):faces.append((row*n+i,row*n+(i+1)%n,(row+1)*n+(i+1)%n,(row+1)*n+i))
    return mesh(name,verts,faces,mat,group,bevel)

def plate(name,points,normal,depth,mat,group,bevel=.009):
    normal=Vector(normal).normalized();points=[Vector(p) for p in points];n=len(points)
    verts=[tuple(p+normal*offset) for offset in [-depth*.5,depth*.5] for p in points]
    return mesh(name,verts,[tuple(reversed(range(n))),tuple(range(n,n*2))]+[(i,(i+1)%n,(i+1)%n+n,i+n) for i in range(n)],mat,group,bevel)

def oriented_box(name,at,size,right,up,forward,mat,group,bevel=.01):
    at=Vector(at);axes=[Vector(right),Vector(up),Vector(forward)]
    signs=[(-1,-1,-1),(1,-1,-1),(1,1,-1),(-1,1,-1),(-1,-1,1),(1,-1,1),(1,1,1),(-1,1,1)]
    verts=[tuple(at+sum((axes[i]*size[i]*corner[i]*.5 for i in range(3)),Vector())) for corner in signs]
    return mesh(name,verts,[(0,3,2,1),(4,5,6,7),(0,1,5,4),(3,7,6,2),(1,2,6,5),(0,4,7,3)],mat,group,bevel)

def gear_stencil(at,tangent,up,normal,group):
    at=Vector(at);t=Vector(tangent);v=Vector(up);n=Vector(normal)
    verts=[];count=48
    for inner in [False,True]:
        for i in range(count):
            angle=i*math.tau/count
            radius=.046 if inner else (.108 if i%4 in [1,2] else .085)
            verts.append(tuple(at+(t*math.cos(angle)+v*math.sin(angle))*radius))
    mesh('Ivory gear identity stencil',verts,[(i,(i+1)%count,(i+1)%count+count,i+count) for i in range(count)],white,group,0)
    cylinder('Gear hub stencil',at-n*.0005,at+n*.0005,.024,white,group,20,bevel=0)

ring_shell('Rounded armored hexagonal monocoque',[(-.25,.92),(-.16,1.0),(.25,.70)],dark,body,.032)
ring_shell('Lower recessed machine skirt',[(-.30,.83),(-.235,.89),(-.19,.87)],dark,body,.018)
# A thin continuous gasket under the roof ties the six cast panels together.
ring_shell('Roof perimeter rubber gasket',[(.234,.731),(.265,.715)],rubber,body,.010)
ring_shell('Small chamfered roof deck',[(.259,.707),(.288,.676)],orange,body,.014)
for i,(x,z) in enumerate(profile):
    nx,nz=profile[(i+1)%6]
    a=Vector((x,-.137,z));b=Vector((nx,-.137,nz));c=Vector((nx*.70,.25,nz*.70));d=Vector((x*.70,.25,z*.70))
    center=(a+b+c+d)/4
    normal=(b-a).cross(d-a).normalized()
    if normal.dot(Vector((center.x,0,center.z)))<0:normal=-normal
    # Deep dark seam, wide round-over, distinct sloped trapezoid panel.
    aa=a.lerp(b,.055).lerp(d.lerp(c,.055),.035)
    bb=b.lerp(a,.055).lerp(c.lerp(d,.055),.035)
    cc=c.lerp(d,.065).lerp(b.lerp(a,.065),.035)
    dd=d.lerp(c,.065).lerp(a.lerp(b,.065),.035)
    corners=[aa+normal*.017,bb+normal*.017,cc+normal*.017,dd+normal*.017]
    plate('Sloping cast orange armor sector %d'%i,corners,normal,.045,orange,body,.021)
    tangent=(bb-aa).normalized();vertical=(dd-aa).normalized()
    for u0 in [.13,.87]:
        for v0 in [.12,.86]:
            p=aa.lerp(bb,u0).lerp(dd.lerp(cc,u0),v0)+normal*.047
            bolt(p,normal,body,.015)
    if i==0:
        gear_stencil(center+normal*.052,tangent,vertical,normal,body)
    elif i in [1,5]:
        # Flush service access panel inset into the sloped cheek.
        p=center+normal*.048
        plate('Recessed angled inspection cover',[p-tangent*.090-vertical*.055,p+tangent*.090-vertical*.055,p+tangent*.090+vertical*.055,p-tangent*.090+vertical*.055],normal,.013,dark,body,.012)
        plate('Inspection latch',[p-tangent*.030-vertical*.017+normal*.009,p+tangent*.030-vertical*.017+normal*.009,p+tangent*.030+vertical*.017+normal*.009,p-tangent*.030+vertical*.017+normal*.009],normal,.014,steel,body,.005)
    elif i==3:
        p=center+normal*.050
        plate('Recessed rear heat outlet',[p-tangent*.16-vertical*.065,p+tangent*.16-vertical*.065,p+tangent*.16+vertical*.065,p-tangent*.16+vertical*.065],normal,.020,rubber,body,.009)
        for k in range(5):
            q=p+vertical*((k-2)*.025)+normal*.014
            plate('Rear louver fin',[q-tangent*.14-vertical*.006,q+tangent*.14-vertical*.006,q+tangent*.14+vertical*.006,q-tangent*.14+vertical*.006],normal,.012,steel,body,.001)
# Roof is a compact service deck; it no longer dominates the whole silhouette.
for side in [-1,1]:
    box('Roof cooling recess',(side*.32,.295,.12),(.18,.014,.32),rubber,body,.008)
    for i in range(7):box('Roof cooling fin',(side*.32,.308,-.015+i*.042),(.15,.021,.013),dark,body,.003)
    for z in [-.37,.40]:
        box('Roof access fastener surround',(side*.27,.296,z),(.12,.016,.13),dark,body,.012)
        bolt((side*.27,.309,z),(0,1,0),body,.013)
# Recessed underside mechanics and segmented cross members.
for z in [-.49,0,.49]:
    box('Underbody cross beam',(0,-.273,z),(.96,.082,.09),dark,body,.011)
    for side in [-1,1]:
        bolt((side*.39,-.318,z),(0,-1,0),body,.017)
for side in [-1,1]:
    for row,z in enumerate([-.68,0,.68]):
        hip=Vector((side*(.79 if row==1 else .46),-.13,z))
        outward=Vector((side,0,0)) if row==1 else Vector((side*.55,0,(-1 if row==0 else 1)*.83)).normalized()
        tangent=Vector((0,1,0)).cross(outward).normalized()
        # Socket socket axes follow the six radial legs, not parallel box sides.
        cylinder('Radial drive isolation boot',hip-outward*.20,hip-outward*.055,.118,rubber,body,24,bevel=.008)
        ring('Radial drive quick-release collar',hip-outward*.067,outward,.128,.098,.026,steel,body,24)
        oriented_box('Cast radial hip cradle',hip-outward*.083-Vector((0,.045,0)),(.28,.17,.21),tangent,(0,1,0),outward,dark,body,.026)
        for s in [-1,1]:
            bolt(hip-outward*.063+tangent*s*.095+Vector((0,.055,0)),(0,1,0),body,.013)
    tube('Protected lower flank loom',[(side*.47,-.215,-.53),(side*.68,-.215,-.21),(side*.69,-.215,.20),(side*.46,-.215,.53)],.020,rubber,body)
# Three separate low camera housings, each with inset reflective lens.
for x in [-.23,.0,.23]:
    box('Individual armored roof camera',(x,.337,-.34),(.13,.10,.12),dark,body,.016)
    cylinder('Camera recess',(x,.338,-.405),(x,.338,-.413),.035,steel,body,20,bevel=0)
    cylinder('Amber camera optic',(x,.338,-.414),(x,.338,-.419),.023,amber,body,20,bevel=0)
    bolt((x+.042,.385,-.34),(0,1,0),body,.008)
for x in [-.20,.20]:
    cylinder('Rear running lens',(x,-.06,.815),(x,-.06,.829),.022,red,body,16,bevel=0)
textmesh('HX-6',(0,.301,-.15),.070,body)
# Tail and gun are separate authored modules with a shared precision helper API.
sys.path.insert(0,str(ROOT/'tools'))
module_metadata={}
for module_name in ['scorpion_tail','scorpion_gun']:
    module_path=ROOT/'tools'/(module_name+'.py')
    if module_path.exists():
        result=importlib.import_module(module_name).build(globals())
        if result:module_metadata.update(result)
    elif '--body-preview' not in sys.argv:
        raise RuntimeError('Required modular asset generator missing: '+str(module_path))

# Mechanical limb templates. Local +Y runs joint to joint; local X is the hinge.
def limb_outline(name,outline,z,depth,mat,group,bevel=.010):
    return plate(name,[(x,y,z) for x,y in outline],(0,0,1),depth,mat,group,bevel)

def limb_bearing(group,at,r,width,painted=True):
    p=Vector(at)
    cylinder('Deep sealed rotary drum',p-Vector((width*.5,0,0)),p+Vector((width*.5,0,0)),r,dark,group,32,bevel=.012)
    # Narrow polished bearing races sit inside thick black caps.
    for side in [-1,1]:
        q=p+Vector((side*(width*.5+.008),0,0))
        ring('Recessed bearing race',q,(1,0,0),r*.84,r*.70,.019,steel,group,24)
        cylinder('Cast rotary cover',q-Vector((.011,0,0)),q+Vector((.011,0,0)),r*.695,orange if painted else dark,group,24,bevel=.008)
        cylinder('Bearing boss',q+Vector((side*.009,0,0)),q+Vector((side*.025,0,0)),r*.34,dark,group,16,bevel=0)
        ring('Bronze bearing seal',q+Vector((side*.027,0,0)),(1,0,0),r*.26,r*.19,.004,brass,group,16)
        bolt(q+Vector((side*.030,0,0)),(side,0,0),group,.014)
        for i in range(3):
            angle=i*math.tau/3
            bolt(q+Vector((side*.013,math.sin(angle)*r*.82,math.cos(angle)*r*.82)),(side,0,0),group,.009)
# Coxa/upper link: cast waisted frame, open clevis, guarded actuator.
limb_bearing(upper,(0,0,0),.136,.31,False)
upper_bearing_geometry=set(groups[upper])
upper_profile=[(-.12,.06),(.12,.06),(.16,.14),(.10,.49),(.115,.61),(.07,.65),(-.07,.65),(-.115,.61),(-.10,.49),(-.16,.14)]
limb_outline('Waisted cast upper backbone',upper_profile,.025,.20,dark,upper,.017)
for side in [-1,1]:
    limb_outline('Orange upper clevis cheek',[(side*x,y) for x,y in [(.085,.115),(.159,.14),(.15,.25),(.115,.49),(.075,.535),(.046,.46),(.073,.24)]],-.105,.035,orange,upper,.010)
    for y in [.18,.43]:bolt((side*.112,y,-.13),(0,0,-1),upper,.012)
    cylinder('Upper tie rod',(side*.133,.17,.08),(side*.094,.58,.04),.024,steel,upper,12,bevel=0)
cylinder('Upper hydraulic barrel',(0,.11,.085),(0,.415,.085),.050,dark,upper,20,bevel=0)
cylinder('Upper hydraulic exposed ram',(0,.40,.085),(0,.615,.085),.026,chrome,upper,12,bevel=0)
ring('Upper actuator gland',(0,.415,.085),(0,1,0),.054,.028,.027,steel,upper,20)
# Distal clevis arms encircle the knee drum owned by the lower template.
for side in [-1,1]:
    limb_outline('Open knee clevis lug',[(side*x,y) for x,y in [(.115,.46),(.176,.49),(.181,.67),(.139,.705),(.105,.66)]],.018,.16,dark,upper,.018)
tube('Upper high pressure hose',[(-.087,.10,.12),(-.10,.24,.16),(-.10,.44,.16),(-.065,.60,.12)],.014,rubber,upper)
# Scorpion has a compact coxa unlike the legacy walker's .67 m upper link.
# Compress only the link length; keep the proximal hinge drum circular.
for obj in groups[upper]:
    if obj not in upper_bearing_geometry:obj.data.transform(Matrix.Diagonal((1,1,.45/.67,1)))
# Broad armored lower leg with an actual U-cutout showing its extended ankle link.
limb_bearing(lower,(0,0,0),.164,.32,True)
lower_outline=[(-.11,.054),(.11,.054),(.176,.105),(.194,.18),(.170,.48),(.14,.614),(.072,.645),(.072,.482),(-.072,.482),(-.072,.645),(-.14,.614),(-.170,.48),(-.194,.18)]
limb_outline('Broad sculpted shin with open clevis cutout',lower_outline,-.121,.068,orange,lower,.015)
# Back frame and ankle tongue can be seen through the true cutout.
for side in [-1,1]:
    limb_outline('Lower structural fork',[(side*x,y) for x,y in [(.073,.055),(.136,.09),(.126,.51),(.105,.63),(.063,.61)]],.02,.17,dark,lower,.013)
    cylinder('Protected shin damper',(side*.153,.13,.076),(side*.124,.49,.076),.026,dark,lower,12,bevel=0)
    cylinder('Shin damper piston',(side*.123,.46,.076),(side*.09,.65,.048),.017,chrome,lower,10,bevel=0)
    for y in [.155,.38,.555]:bolt((side*(.143 if y<.45 else .110),y,-.166),(0,0,-1),lower,.012)
limb_outline('Exposed forged ankle tongue',[(-.055,.425),(.055,.425),(.075,.49),(.063,.68),(.042,.744),(-.042,.744),(-.063,.68),(-.075,.49)],-.013,.14,steel,lower,.019)
limb_bearing(lower,(0,.73,0),.081,.255,False)
# Raised shoulder fairing above the cylinder, a sculpted bridge rather than a box.
for side in [-1,1]:
    limb_outline('Orange shoulder bridge',[(side*x,y) for x,y in [(.097,-.124),(.164,-.081),(.179,.052),(.145,.121),(.101,.089),(.119,-.028),(.079,-.076)]],-.002,.17,orange,lower,.010)
tube('Protected shin harness',[(.072,.04,.11),(.091,.19,.137),(.087,.39,.13),(.034,.64,.09)],.014,rubber,lower)
# Tripartite forged toes and curved ankle yoke, all based at floor contact.
foot_shape=[(-.15,-.17),(.15,-.17),(.175,-.10),(.16,.115),(.115,.16),(-.115,.16),(-.16,.115),(-.175,-.10)]
foot_verts=[(x*.95,.012,z) for x,z in foot_shape]+[(x*.85,.10,z*.87) for x,z in foot_shape]
mesh('Forged chamfered foot sole',foot_verts,[tuple(reversed(range(8))),tuple(range(8,16))]+[(i,(i+1)%8,(i+1)%8+8,i+8) for i in range(8)],dark,foot,.020)
for x in [-.112,0,.112]:
    toe_profile=[(x-.049,-.291),(x+.049,-.291),(x+.054,-.243),(x+.047,-.10),(x-.047,-.10),(x-.054,-.243)]
    toe_verts=[(xx,.012,zz) for xx,zz in toe_profile]+[(xx,.074 if zz<-.24 else .105,zz) for xx,zz in toe_profile]
    mesh('Individual beveled grip toe',toe_verts,[(0,5,4,3,2,1),(6,7,8,9,10,11)]+[(i,(i+1)%6,(i+1)%6+6,i+6) for i in range(6)],steel,foot,.012)
    for z in [-.254,-.19]:box('Toe traction inset',(x,.092,z),(.068,.009,.014),dark,foot,.002)
    bolt((x,.112,-.129),(0,1,0),foot,.012)
for side in [-1,1]:
    plate('Ankle upright clevis',[(side*.115,.058,-.10),(side*.115,.21,-.042),(side*.115,.252,.041),(side*.115,.10,.121)],(1,0,0),.042,dark,foot,.016)
    cylinder('Ankle fastener cover',(side*.132,.18,.015),(side*.151,.18,.015),.054,steel,foot,16,bevel=0)
    bolt((side*.155,.18,.015),(side,0,0),foot,.022)

def finalize(group):
    items=groups[group]
    if not items:return
    bpy.ops.object.select_all(action='DESELECT')
    for obj in items:
        obj.select_set(True);bpy.context.view_layer.objects.active=obj
        for mod in list(obj.modifiers):bpy.ops.object.modifier_apply(modifier=mod.name)
        obj.select_set(False)
    for obj in items:obj.select_set(True)
    bpy.context.view_layer.objects.active=items[0]
    bpy.ops.object.join();obj=bpy.context.object
    world=obj.matrix_world.copy()
    obj.data.transform(group.matrix_world.inverted()@world)
    obj.parent=group;obj.matrix_parent_inverse=Matrix.Identity(4);obj.matrix_basis=Matrix.Identity(4)
    obj.name=group.name+'Surface'
    # Every polygon has intentional weighted normals; preserve them in glTF.
    bpy.ops.object.select_all(action='DESELECT')

for group in list(groups):finalize(group)

# A two degree depression meets the tops of nearby machines. Rotate the whole
# socket assembly around the muzzle, so the rotor's own local Z remains axial.
gun_muzzle=gv((.66,.27,-1.72))
gun.matrix_world=(Matrix.Translation(gun_muzzle) @ Matrix.Rotation(-.035,4,'X')
                  @ Matrix.Translation(-gun_muzzle) @ gun.matrix_world)
bpy.context.view_layer.update()

def descendants(obj):
    return [obj]+[child for c in obj.children for child in descendants(c)]

def export(obj,filename):
    bpy.ops.object.select_all(action='DESELECT')
    for item in descendants(obj):item.select_set(True)
    bpy.context.view_layer.objects.active=obj
    bpy.ops.export_scene.gltf(filepath=str(RUNTIME/filename),export_format='GLB',use_selection=True,
        export_yup=True,export_apply=True,export_texcoords=True,export_normals=True,
        export_materials='EXPORT',export_cameras=False,export_lights=False,
        export_animations=False,export_extras=True)
    bpy.ops.object.select_all(action='DESELECT')
    # glTF permits external image URIs inside a GLB. Share the material maps
    # between all four meshes rather than asking Godot to extract four copies.
    path=RUNTIME/filename
    raw=path.read_bytes();json_len=struct.unpack_from('<I',raw,12)[0]
    document=json.loads(raw[20:20+json_len])
    binary_start=20+json_len+8
    binary=raw[binary_start:]
    image_views={im['bufferView'] for im in document.get('images',[]) if 'bufferView' in im}
    for im in document.get('images',[]):
        im.pop('bufferView',None);im.pop('mimeType',None)
        im['uri']=im['name']+'.png'
        if not (RUNTIME/im['uri']).exists():raise RuntimeError('Missing shared texture '+im['uri'])
    remap={};views=[];packed=bytearray()
    for i,view in enumerate(document['bufferViews']):
        if i in image_views:continue
        while len(packed)%4:packed.append(0)
        old_offset=view.get('byteOffset',0);chunk=binary[old_offset:old_offset+view['byteLength']]
        new_view=dict(view);new_view['byteOffset']=len(packed);remap[i]=len(views);views.append(new_view);packed.extend(chunk)
    for accessor in document.get('accessors',[]):
        if 'bufferView' in accessor:accessor['bufferView']=remap[accessor['bufferView']]
    document['bufferViews']=views;document['buffers'][0]['byteLength']=len(packed)
    while len(packed)%4:packed.append(0)
    jb=json.dumps(document,separators=(',',':')).encode('utf8')
    while len(jb)%4:jb+=b' '
    path.write_bytes(struct.pack('<4sII',b'glTF',2,12+8+len(jb)+8+len(packed))
        +struct.pack('<I4s',len(jb),b'JSON')+jb+struct.pack('<I4s',len(packed),b'BIN\0')+packed)

export(root,'scorpion.glb')
export(upper,'leg_upper.glb');export(lower,'leg_lower.glb');export(foot,'leg_foot.glb')

def triangles(obj):
    return sum(len(p.vertices)-2 for node in descendants(obj) if node.type=='MESH' for p in node.data.polygons)
manifest={
 'generator':'tools/build-scorpion.py', 'authoring':'Godot metres, Y up, -Z forward; multiply BotScale exactly once',
 'body_envelope':[1.6,.5,2.0],
 'hierarchy':{o.name:{'parent':o.parent.name if o.parent else None,'position':godot(o.matrix_local.translation),'rest_rotation':[-.035,0,0] if o==gun else [0,0,0]} for o in [root,body,tail0,tail1,tail2,hammer,gun,rotor]+([tail_extension] if 'tail_extension' in globals() else [])},
 'hammer_center':[0,1.25,-1.12], 'hammer_size':[.69,.62,.50],
 'minigun_muzzle':[.66,.27,-1.72], 'minigun_spin_axis':'local Z',
 'legs':{'upper_length':.45,'lower_length':.73,'segment_axis':'+Y','hinge_axis':'local X tangent to radial stance','foot_origin':'ground contact','ankle_height':.18},
 'triangles':{'body_tail_gun':triangles(root),'leg_upper':triangles(upper),'leg_lower':triangles(lower),'leg_foot':triangles(foot)},
 'materials':'Original authored shared 1024px base color / metallic-roughness / tangent normal maps referenced by all GLBs; metallic surfaces reflect scene lighting.'}
manifest['triangles']['assembled_six_legs']=triangles(root)+6*(triangles(upper)+triangles(lower)+triangles(foot))
manifest.update(module_metadata)
if 'gun_detail_manifest' in globals():manifest['gun_detail']=gun_detail_manifest
manifest['body_collider']={'profile_xz':profile,'rings_y_scale':[[-.25,.92],[-.16,1.0],[.25,.70]]}
(RUNTIME/'scorpion_manifest.json').write_text(json.dumps(manifest,indent=2))
print('SCORPION_ASSET_MANIFEST',json.dumps(manifest['triangles']))

# Assemble six mechanical legs for source/beauty only; gameplay poses exported parts.
for prototype in [upper,lower,foot]:
    for node in descendants(prototype):node.hide_render=True

def clone_part(original,name,at,direction=None,outward=None):
    duplicate=original.copy();duplicate.name=name;bpy.context.collection.objects.link(duplicate)
    duplicate.parent=None;duplicate.location=gv(at);duplicate.hide_render=False
    if direction is not None:
        d=Vector(direction).normalized();right=Vector((0,1,0)).cross(outward).normalized();forward=right.cross(d)
        # Columns correspond to the Godot basis transformed to Blender.
        conv=Matrix(((1,0,0),(0,0,-1),(0,1,0)))
        rot=Matrix((right,d,forward)).transposed()
        duplicate.rotation_mode='QUATERNION';duplicate.rotation_quaternion=(conv@rot@conv.inverted()).to_quaternion()
    elif outward is not None:
        conv=Matrix(((1,0,0),(0,0,-1),(0,1,0)))
        right=Vector(outward).cross(Vector((0,1,0))).normalized()
        rot=Matrix((right,Vector((0,1,0)),-Vector(outward))).transposed()
        duplicate.rotation_mode='QUATERNION';duplicate.rotation_quaternion=(conv@rot@conv.inverted()).to_quaternion()
    for child in original.children:
        c=child.copy();c.data=child.data;c.parent=duplicate;c.hide_render=False;bpy.context.collection.objects.link(c)
    return duplicate

for side in [-1,1]:
    for i,z in enumerate([-.68,0,.68]):
        hip=Vector((side*(.79 if i==1 else .46),-.13,z))
        f=Vector((side*(1.40 if i==1 else .90),-.95,0 if i==1 else (-1.1 if i==0 else 1.1)))
        outward=Vector((f.x-hip.x,0,f.z-hip.z)).normalized()
        ankle=f+Vector((0,.18,0));direction=(ankle-hip).normalized();dist=(ankle-hip).length
        along=(.45**2-.73**2+dist**2)/(2*dist)
        bend=(outward-direction*outward.dot(direction)).normalized()
        knee=hip+direction*along+bend*math.sqrt(max(0,.45**2-along**2))
        clone_part(upper,'PreviewUpper_%s_%s'%(side,i),hip,knee-hip,outward)
        clone_part(lower,'PreviewLower_%s_%s'%(side,i),knee,ankle-knee,outward)
        clone_part(foot,'PreviewFoot_%s_%s'%(side,i),f,outward=outward)

# Studio floor and arena-inspired reflection cards belong only to source preview.
floor_mat=simple('Preview light grey studio',(.69,.71,.73),.03,.62)
bpy.ops.mesh.primitive_plane_add(size=200,location=(0,0,-.955))
floor_obj=bpy.context.object;floor_obj.name='PreviewFloor';floor_obj.data.materials.append(floor_mat)
def light(name,at,energy,color,size,target=(0,.5,0)):
    data=bpy.data.lights.new(name,'AREA');data.energy=energy;data.color=color;data.shape='DISK';data.size=size
    obj=bpy.data.objects.new(name,data);bpy.context.collection.objects.link(obj);obj.location=gv(at)
    obj.rotation_euler=(gv(target)-obj.location).to_track_quat('-Z','Y').to_euler()
light('Large soft key',(-3.5,5,-4),700,(1,.93,.85),4)
light('Cool reflection strip',(3,3.8,.5),750,(.83,.91,1),3)
light('Rim light',(-1,3.0,3),800,(1,.93,.82),2.0)
light('Front softbox',(1.5,2,-4),450,(.94,.97,1),3.5)
world=bpy.context.scene.world or bpy.data.worlds.new('Scorpion studio');bpy.context.scene.world=world
world.use_nodes=True;world.node_tree.nodes['Background'].inputs[0].default_value=(.55,.58,.64,1)
world.node_tree.nodes['Background'].inputs[1].default_value=.6
camera_data=bpy.data.cameras.new('BeautyCamera');camera=bpy.data.objects.new('BeautyCamera',camera_data);bpy.context.collection.objects.link(camera)
camera.location=gv((4.35,2.65,-5.6));target=gv((0,.40,-.05));camera.rotation_euler=(target-camera.location).to_track_quat('-Z','Y').to_euler();camera_data.lens=48
bpy.context.scene.camera=camera
scene=bpy.context.scene;scene.render.engine='CYCLES';scene.cycles.samples=64;scene.cycles.use_denoising=True
try:
    prefs=bpy.context.preferences.addons['cycles'].preferences;prefs.compute_device_type='OPTIX';prefs.get_devices()
    for device in prefs.devices:device.use=device.type!='CPU'
    scene.cycles.device='GPU'
except Exception:pass
scene.render.resolution_x=1600;scene.render.resolution_y=1250;scene.render.resolution_percentage=100
scene.view_settings.view_transform='AgX';scene.view_settings.look='AgX - Medium High Contrast'
scene.render.image_settings.file_format='PNG';scene.render.filepath=str(SOURCE/'scorpion_beauty.png')
for image in bpy.data.images:
    if image.source=='FILE':image.pack()
bpy.ops.wm.save_as_mainfile(filepath=str(SOURCE/'scorpion.blend'))
if '--no-render' not in sys.argv:
    bpy.ops.render.render(write_still=True)
    camera_data.type='ORTHO';camera_data.ortho_scale=4.15
    scene.render.resolution_x=1400;scene.render.resolution_y=1400
    for label,at,target in [('front',(0,.43,-8),(0,.43,0)),('left',(-8,.43,0),(0,.43,0)),('top',(0,8,.001),(0,0,0))]:
        camera.location=gv(at);camera.rotation_euler=(gv(target)-camera.location).to_track_quat('-Z','Y').to_euler()
        scene.render.filepath=str(SOURCE/('scorpion_'+label+'.png'))
        bpy.ops.render.render(write_still=True)
print('SCORPION BUILD COMPLETE')
